development:
  adapter: postgresql
  database: fhl_rails_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: fhl_rails_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fhl_rails_production
  pool: 5
  timeout: 5000
